<flight plan>           ::= <event handler> | <event handler> <flight plan>
<event handler>         ::= on <inline-space> <event name> <inline-space> [ <whitespace> <parameter list> <whitespace> ] <whitespace> { <whitespace> <code> <whitespace> }
<inline-space>          ::= " " | " " <inline-space>
<optional-inline-space> ::= "" | <inline-space>
<whitespace>            ::= <inline-space> | <newline> | <inline-space> <whitespace> | <newline> <whitespace>
<event name>            ::= <word> | <word> " " <event name>
<word>                  ::= "" | <word> <letter>
<letter>                ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
<code>                  ::= <whitespace> <statement> | <whitespace> <statement> <newline> <code>
<newline>               ::= "\n"
<statement>             ::= <variable assignment> | <variable reassignment> | <control structure> | <send event> | "do nothing"
<variable assignment>   ::= <variable name> <inline-space> "is" <inline-space> <expression>
<variable reassignment> ::= <variable name> <inline-space> "is now" <inline-space> <expression>
<control structure>     ::= "if" <inline-space> <variable> <inline-space> "{" <newline> <code> <newline> "}" <newline> "else {" <newline> <code> <newline> "}"
<expression>            ::= <variable-or-literal> <operator> <variable-or-literal>
<variable-or-literal>   ::= <variable> | <literal>
<variable>              ::= <word> | <word> "-" <variable>
<literal>               ::= <non-whitespace> | <non-whitespace> <literal>
<non-whitespace>        ::= «any non space symbol»
<send event>            ::= "send" <inline-whitespace> <event name> <inline-whitespace> "[" <inline-whitespace> <argument list>  <inline-whitespace> "]" <scheduled time>
<scheduled time>        ::= "now" | "in" <inline-whitespace> <variable-or-literal>
<parameter list>        ::= "" | <parameter name> ":" <optional-inline-space> <parameter list>
<argument list>         ::= "" | <parameter name> ":" <parameter value> <optional-inline-space> <parameter value>
<parameter name>        ::= <word> | <word> "-" <parameter name>
<parameter value>       ::= <variable-or-literal>
