const path                 = require("path");
const Merge                = require("webpack-merge");
const CommonConfig         = require("./webpack.common.config.js");
const MiniCssExtractPlugin = require("mini-css-extract-plugin")
const HtmlPlugin           = require("html-webpack-plugin");
const ImageCopying         = require("./copy-images.config.js");


module.exports = Merge(CommonConfig, {
  output: {
    path: path.join(__dirname, "../production"),
    filename: "bundle-[contenthash].js"
  },
  plugins: [
    new MiniCssExtractPlugin({ filename: "styles-[contenthash].css" }),
    ImageCopying("production"),
    new HtmlPlugin({
      template: "./src/html/index.html",
      minify: {
        "caseSensitive": false,
        "collapseBooleanAttributes": true,
        "collapseInlineTagWhitespace": false,
        "collapseWhitespace": true,
        "conservativeCollapse": true,
        "continueOnParseError": false,
        "decodeEntities": true,
        "html5": true,
        "ignoreCustomFragments": [],
        "includeAutoGeneratedTags": false,
        "keepClosingSlash": false,
        "maxLineLength": 0,
        "minifyCSS": true,
        "minifyJS": true,
        "preserveLineBreaks": false,
        "preventAttributesEscaping": false,
        "processConditionalComments": true,
        "processScripts": [ ],
        "removeAttributeQuotes": false,
        "removeComments": true,
        "removeEmptyAttributes": true,
        "removeEmptyElements": true,
        "removeOptionalTags": false,
        "removeRedundantAttributes": true,
        "removeScriptTypeAttributes": true,
        "removeStyleLinkTypeAttributes": true,
        "removeTagWhitespace": false,
        "sortAttributes": true,
        "sortClassName": true,
        "trimCustomFragments": true,
        "useShortDoctype": true
      }
    })
  ],
  optimization: {
    minimize: true
  }
});
